#!/usr/ruby-enterprise/bin/ruby

require 'rubygems'
require 'treetop'
require 'polyglot'
require 'pine_addressbook'

parser = PineAddressbookParser.new

tree = parser.parse(File.read('abook-test'))

if tree.nil?
  $stderr.puts parser.failure_reason
else
  puts tree.to_csv
end

